import { google } from 'googleapis';
import { getWorkspaceClient } from './workspaceAuth';
import { logger } from '../utils/logger';

// 🛡️ SECURITY: Strict calendar event scope.
const CALENDAR_SCOPES = ['https://www.googleapis.com/auth/calendar.events'];

/**
 * Generates an encrypted Google Meet room and schedules the synchronous triage consult.
 * @param adminEmail The Workspace physician/admin email to impersonate.
 * @param patientId The secure, alphanumeric patient identifier.
 */
export const scheduleTelehealthConsult = async (adminEmail: string, patientId: string) => {
  try {
    logger.info('Authorizing Calendar API via Domain-Wide Delegation...', { target: 'Calendar' });
    const auth = getWorkspaceClient(adminEmail, CALENDAR_SCOPES);
    const calendar = google.calendar({ version: 'v3', auth });

    logger.info('Initiating secure telehealth Meet generation.', { patientId });

    // Schedule the consult for exactly 5 minutes from now. Fast triage.
    const startTime = new Date();
    startTime.setMinutes(startTime.getMinutes() + 5);
    const endTime = new Date(startTime);
    endTime.setMinutes(endTime.getMinutes() + 20); // 15 minute block

    // 🔒 We do NOT put patient names or PHI in the calendar event. Identifier only.
    const event = {
      summary: `[SECURE] Clinical Triage: ${patientId}`,
      description: `Automated telehealth consult generated by MED~USA. Initiate synchronous transfer for ${patientId}.`,
      start: { dateTime: startTime.toISOString() },
      end: { dateTime: endTime.toISOString() },
      conferenceData: {
        createRequest: {
          requestId: `medusa-meet-${patientId}-${Date.now()}`,
          conferenceSolutionKey: { type: 'hangoutsMeet' }
        }
      }
    };

    // Push the event to the primary calendar and request a Meet link
    const response = await calendar.events.insert({
      calendarId: 'primary',
      conferenceDataVersion: 1, // REQUIRED to generate the Google Meet link
      requestBody: event,
    });

    const meetLink = response.data.hangoutLink;
    if (!meetLink) throw new Error('Calendar API failed to generate a Google Meet link.');

    logger.info('Telehealth intercept locked. Meet generated.', { patientId });
    return meetLink;
  } catch (error) {
    logger.error('Telehealth provisioning catastrophic failure.', { 
      patientId, 
      error: error instanceof Error ? error.message : 'Unknown Error' 
    });
    throw error;
  }
};
